# Change these first
owner: dstroot
repo: vds_uptime

# Add your sites here
sites:
  - name: Verite Data Science
    url: https://veritedatascience.com/
  - name: React Instagram
    url: https://affectionate-aryabhata-c22561.netlify.app/
  - name: Storybook
    url: https://zealous-fermat-ea58fd.netlify.app/
  - name: React Infinite Scrolling
    url: https://modest-panini-61a8ce.netlify.app/
  - name: React Dark Mode (Cloudflare)
    url: https://react-darkmode.burley.workers.dev/
  - name: "Dan Stroot's Blog"
    url: https://danstroot.com/
  - name: Site Monitor
    url: https://dstroot.github.io/vds_uptime/
    
# Add downtime notifications
# https://upptime.js.org/docs/notifications
notifications:
  - type: twilio

# Configure your status website
# http://localhost:3000/docs/configuration#status-website
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /vds_uptime
  logoUrl: https://raw.githubusercontent.com/dstroot/vds_uptime/master/icon.svg
  name: VDS Uptime
  theme: light
  introTitle: "Verite Data Science Uptime"
  introMessage: "INNOVATION, POWERED BY DATA"
  navbar:
    - title: Verite Data Science
      href: https://veritedatascience.com/
  # - title: Status
  #   href: https://dstroot.github.io/VDS_uptime/

i18n:
  footer: Designed and built in California with all the love in the world.
  # footer: This page is [open source]($REPO), powered by [Upptime](https://upptime.js.org)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
