# See https://upptime.js.org/docs/configuration
owner: dstroot      # GitHub username
repo: vds_uptime    # GitHub repository name

# Site(s) to monitor
sites:
  - name: Verite Data Science
    url: https://veritedatascience.com/
  - name: Verite Data Science (Netlify)
    url: https://modest-turing-778882.netlify.app/
  - name: React Instagram
    url: https://affectionate-aryabhata-c22561.netlify.app/
  - name: Storybook
    url: https://zealous-fermat-ea58fd.netlify.app/
  - name: React Infinite Scrolling
    url: https://modest-panini-61a8ce.netlify.app/
  - name: "Dan Stroot's Blog"
    url: https://danstroot.com/
  - name: Site Monitor
    url: https://dstroot.github.io/vds_uptime/
  - name: Pacific Life
    url: https://www.pacificlife.com/
    
# Users to assign downtime issues (optional)
assignees: 
  - dstroot
    
# Add downtime notifications
# https://upptime.js.org/docs/notifications
notifications:
  - type: twilio

# Configure your status website
# http://localhost:3000/docs/configuration#status-website
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /vds_uptime
  
  metaTags:
  - name: "color-scheme"
    content: "dark light"
  - name: "robots"
    content: "noindex"
    
  # custom HTML.  Note: You want to have *one string* even if you have multiple tags
  customHeadHtml: "<meta charset=\"UTF-8\">"
  customBodyHtml: "<!-- any custom HTML to append at the top of <body> -->"
  
  logoUrl: https://raw.githubusercontent.com/dstroot/vds_uptime/master/icon.svg
  name: VDS Uptime
  
  # theme: ocean   # Available themes are light, dark, or ocean.
  themeUrl: https://modest-panini-61a8ce.netlify.app/theme.css
  
  # you can use **markdown** in the fields below
  introTitle: "Verite Data Science Uptime"
  introMessage: "INNOVATION, POWERED BY DATA"
  
  # You can customize the navbar top-level navigation links
  navbar:
    - title: Verite Data Science
      href: https://veritedatascience.com/
  # - title: Status
  #   href: https://dstroot.github.io/VDS_uptime/

i18n:
  footer: Designed and built in California with all the love in the world.
  # footer: This page is [open source]($REPO), powered by [Upptime](https://upptime.js.org)
