# Change these first
owner: dstroot
repo: VDS_uptime

# Add your sites here
sites:
  - name: Verite Data Science
    url: https://veritedatascience.com/
  - name: React Instagram
    url: https://affectionate-aryabhata-c22561.netlify.app/
  - name: Storybook
    url: https://zealous-fermat-ea58fd.netlify.app/
  - name: React Infinite Scrolling
    url: https://modest-panini-61a8ce.netlify.app/
  - name: React Dark Mode (Cloudflare)
    url: https://react-darkmode.burley.workers.dev/
  - name: "Dan Stroot's Blog"
    url: https://danstroot.com/

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /VDS_uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: VDS Uptime
  introTitle: "Verite Data Science Uptime"
  introMessage: "INNOVATION, POWERED BY DATA"
  navbar:
    - title: Verite Data Science
      href: https://veritedatascience.com/
#     - title: Status
#       href: https://dstroot.github.io/VDS_uptime/
i18n:
  footer: This page is...
  # footer: This page is [open source]($REPO), powered by [Upptime](https://upptime.js.org)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
