# Change these first
owner: dstroot
repo: VDS_uptime

# Add your sites here
sites:
  - name: Verite Data Science
    url: https://veritedatascience.com/

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /VDS_uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: VDS Uptime
  introTitle: "Verite Data Science Uptime"
  introMessage: "INNOVATION, POWERED BY DATA"
  navbar:
    - title: Verite Data Science
      href: https://veritedatascience.com/
#     - title: Status
#       href: https://dstroot.github.io/VDS_uptime/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
